name: summerschool
channels:
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0=cpu_0
  - anyio=4.0.0=pyhd8ed1ab_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py311h5547dcb_3
  - arrow=1.2.3=pyhd8ed1ab_0
  - asttokens=2.4.0=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - babel=2.12.1=pyhd8ed1ab_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - blas=2.118=openblas
  - blas-devel=3.9.0=18_osx64_openblas
  - bleach=6.0.0=pyhd8ed1ab_0
  - brotli=1.1.0=h0dc2134_0
  - brotli-bin=1.1.0=h0dc2134_0
  - brotli-python=1.1.0=py311hdf8f085_0
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2023.7.22=h8857fd0_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.16.0=h0ab9d94_1001
  - catboost=1.2.1=py311h6eed73b_0
  - cctools_osx-64=973.0.1=h3e07e27_2
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.15.1=py311ha86e640_3
  - charset-normalizer=3.2.0=pyhd8ed1ab_0
  - clang=14.0.6=h694c41f_1
  - clang-14=14.0.6=default_hdb78580_1
  - clang_osx-64=14.0.6=h3113cd8_6
  - clangxx=14.0.6=default_hdb78580_1
  - clangxx_osx-64=14.0.6=h6f97653_6
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - cmdstan=2.31.0=h33b0451_0
  - cmdstanpy=1.1.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.4=pyhd8ed1ab_0
  - compiler-rt=14.0.6=hda8b6b8_0
  - compiler-rt_osx-64=14.0.6=h8d5cb93_0
  - contourpy=1.1.0=py311h5fe6e05_0
  - convertdate=2.4.0=pyhd8ed1ab_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cython=3.0.2=py311hdf8f085_0
  - debugpy=1.7.0=py311hdf8f085_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - ephem=4.1.4=py311h5547dcb_0
  - exceptiongroup=1.1.3=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=hf0c8a7f_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.94=h10f422b_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.42.1=py311h2725bcf_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=hd8bbffd_0
  - fribidi=1.0.10=hbcb3906_0
  - fsspec=2023.9.0=pyh1a96a4e_0
  - future=0.18.3=pyhd8ed1ab_0
  - gdk-pixbuf=2.42.10=h6c40b1e_0
  - gettext=0.21.1=h8a4c099_0
  - giflib=5.2.1=hb7f2c08_3
  - glib=2.69.1=hfff2838_2
  - graphite2=1.3.14=he9d5cce_1
  - graphviz=2.50.0=h196fa6a_0
  - gts=0.7.6=h2684ab5_0
  - harfbuzz=4.3.0=hffc734d_1
  - holidays=0.32=pyhd8ed1ab_0
  - icu=58.2=h0a44026_1000
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - importlib_resources=6.0.1=pyhd8ed1ab_0
  - ipykernel=6.25.2=pyh1050b4e_0
  - ipython=8.15.0=pyh31c8845_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jedi=0.19.0=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.3.2=pyhd8ed1ab_0
  - jpeg=9e=hb7f2c08_3
  - json5=0.9.14=pyhd8ed1ab_0
  - jsonpointer=2.0=py_0
  - jsonschema=4.19.0=pyhd8ed1ab_1
  - jsonschema-specifications=2023.7.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.19.0=pyhd8ed1ab_1
  - jupyter-lsp=2.2.0=pyhd8ed1ab_0
  - jupyter_client=8.3.1=pyhd8ed1ab_0
  - jupyter_core=5.3.1=py311h6eed73b_0
  - jupyter_events=0.7.0=pyhd8ed1ab_2
  - jupyter_server=2.7.3=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyterlab=4.0.5=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.24.0=pyhd8ed1ab_0
  - kiwisolver=1.4.5=py311h5fe6e05_0
  - lcms2=2.15=h29502cd_0
  - ld64_osx-64=609=hfd63004_13
  - ldid=2.1.2=h6a69015_3
  - lerc=3.0=he9d5cce_0
  - libblas=3.9.0=18_osx64_openblas
  - libbrotlicommon=1.1.0=h0dc2134_0
  - libbrotlidec=1.1.0=h0dc2134_0
  - libbrotlienc=1.1.0=h0dc2134_0
  - libcblas=3.9.0=18_osx64_openblas
  - libclang-cpp14=14.0.6=default_hdb78580_1
  - libcxx=16.0.6=hd57cbcb_0
  - libdeflate=1.17=hb664fd8_0
  - libexpat=2.5.0=hf0c8a7f_1
  - libffi=3.4.4=hecd8cb5_0
  - libgd=2.3.3=he7e2580_1
  - libgfortran=5.0.0=13_2_0_h97931a8_1
  - libgfortran5=13.2.0=h2873a65_1
  - libiconv=1.17=hac89ed1_0
  - liblapack=3.9.0=18_osx64_openblas
  - liblapacke=3.9.0=18_osx64_openblas
  - libllvm12=12.0.1=hd011deb_2
  - libllvm14=14.0.6=h91fad77_3
  - libopenblas=0.3.24=openmp_h48a4ad5_0
  - libpng=1.6.39=h6c40b1e_0
  - libprotobuf=3.20.3=hfff2838_0
  - librsvg=2.54.4=h52d90eb_0
  - libsodium=1.0.18=hbcb3906_1
  - libtiff=4.5.1=hcec6c5f_0
  - libtool=2.4.7=hf0c8a7f_0
  - libuv=1.46.0=h0c2f820_0
  - libwebp=1.2.4=h70a068d_1
  - libwebp-base=1.2.4=h6c40b1e_1
  - libxgboost=1.7.6=cpu_h72f100a_2
  - libxml2=2.9.14=hbf8cd5e_0
  - lightgbm=4.0.0=py311h93c27bc_0
  - lightning-utilities=0.9.0=pyhd8ed1ab_0
  - llvm-openmp=16.0.6=hff08bdf_0
  - llvm-tools=14.0.6=he0576d7_3
  - llvmlite=0.40.0=py311hfff2838_0
  - lunarcalendar=0.0.9=py_0
  - lz4-c=1.9.4=hf0c8a7f_0
  - make=4.3=h22f3db7_1
  - markupsafe=2.1.3=py311h2725bcf_0
  - matplotlib-base=3.7.1=py311h2bf763f_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=3.0.1=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclient=0.8.0=pyhd8ed1ab_0
  - nbconvert-core=7.8.0=pyhd8ed1ab_0
  - nbformat=5.9.2=pyhd8ed1ab_0
  - ncurses=6.4=hcec6c5f_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - nfoursid=1.0.1=pyhd8ed1ab_0
  - ninja=1.11.1=hb8565cd_0
  - notebook-shim=0.2.3=pyhd8ed1ab_0
  - numba=0.57.1=py311h5a8220d_0
  - numpy=1.24.4=py311hc44ba51_0
  - openblas=0.3.24=openmp_hd7704e8_0
  - openssl=3.1.2=h8a1eda9_0
  - overrides=7.4.0=pyhd8ed1ab_0
  - packaging=23.1=pyhd8ed1ab_0
  - pandas=2.1.0=py311hab14417_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.50.7=h80fe9ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pcre=8.45=he49afe7_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py311hcec6c5f_0
  - pip=23.2.1=py311hecd8cb5_0
  - pixman=0.38.0=h01d97ff_1003
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=3.10.0=pyhd8ed1ab_0
  - plotly=5.16.1=pyhd8ed1ab_0
  - pmdarima=2.0.3=py311h5547dcb_0
  - pooch=1.7.0=pyha770c72_3
  - prometheus_client=0.17.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - prophet=1.1.4=py311h7966749_0
  - protobuf=3.20.3=py311h814d153_1
  - psutil=5.9.5=py311h5547dcb_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-xgboost=1.7.6=cpu_py311hedae6b8_2
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.16.1=pyhd8ed1ab_0
  - pymeeus=0.5.12=pyhd8ed1ab_0
  - pyobjc-core=9.2=py311hf110eff_0
  - pyobjc-framework-cocoa=9.2=py311hf110eff_0
  - pyod=1.1.0=pyhd8ed1ab_0
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.4=hf27a42d_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.18.0=pyhd8ed1ab_0
  - python-graphviz=0.20.1=pyh22cad53_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.11=2_cp311
  - pytorch=1.13.1=cpu_py311h9e40b02_0
  - pytorch-lightning=2.0.8=pyhd8ed1ab_0
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py311h2725bcf_0
  - pyzmq=25.1.1=py311h5dacc12_0
  - readline=8.2=hca72f7f_0
  - referencing=0.30.2=pyhd8ed1ab_0
  - requests=2.31.0=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.10.2=py311h299eb51_0
  - scikit-learn=1.3.0=py311h83feae1_0
  - scipy=1.11.2=py311h16c3c4d_0
  - send2trash=1.8.2=pyhd1c38e8_0
  - setuptools=68.0.0=py311hecd8cb5_0
  - shap=0.42.1=py311hab14417_0
  - sigtool=0.1.3=h88f4db0_0
  - six=1.16.0=pyh6c4a22f_0
  - slicer=0.0.7=pyhd8ed1ab_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sqlite=3.41.2=h6c40b1e_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsforecast=1.4.0=pyhd8ed1ab_0
  - statsmodels=0.14.0=py311h4a70a88_1
  - tapi=1100.0.11=h9ce4665_0
  - tbats=1.1.3=pyhd8ed1ab_0
  - tbb=2021.10.0=h1c7c39f_0
  - tbb-devel=2021.10.0=h1c7c39f_0
  - tenacity=8.2.3=pyhd8ed1ab_0
  - tensorboardx=2.6.2.2=pyhd8ed1ab_0
  - terminado=0.17.1=pyhd1c38e8_0
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h5d9f67b_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - torchmetrics=1.1.1=pyhd8ed1ab_0
  - tornado=6.3.3=py311h2725bcf_0
  - tqdm=4.66.1=pyhd8ed1ab_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.7.1=hd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzdata=2023c=h04d1e81_0
  - u8darts=0.25.0=pyhd8ed1ab_1
  - u8darts-all=0.25.0=pyhd8ed1ab_1
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=2.0.4=pyhd8ed1ab_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webcolors=1.13=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - websocket-client=1.6.2=pyhd8ed1ab_0
  - wheel=0.38.4=py311hecd8cb5_0
  - xarray=2023.8.0=pyhd8ed1ab_0
  - xgboost=1.7.6=cpu_py311hedae6b8_2
  - xz=5.4.2=h6c40b1e_0
  - yaml=0.2.5=h0d85af4_2
  - zeromq=4.3.4=he49afe7_1
  - zipp=3.16.2=pyhd8ed1ab_0
  - zlib=1.2.13=h4dc903c_0
  - zstd=1.5.5=hc035e20_0
